# Використовуємо офіційний образ Node.js
FROM node:14

# Створюємо робочий каталог
WORKDIR /usr/src/app

# Копіюємо файли з вашого проекту в контейнер
COPY package*.json ./
COPY index.js ./

# Встановлюємо залежності
RUN npm install

CMD ["npm", "start"]

# Відкриваємо порт, на якому працює ваш сервер
EXPOSE 3000

