version: "3.9"
services:
  lab1:
    container_name: node_con_lb1
    image: "node-lb1"
    build:
      context: .
      dockerfile: dockerfile
    environment:
        - "MYSQL_DATABASE=test_db_node"
        - "MYSQL_USER=admin"
        - "MYSQL_PASSWORD=password"
    volumes:
      - data:/var/lib/mysql
    ports:
      - '3000:3000'
      - '3307:3306'

volumes:
  data: