# Використовуємо офіційний образ Node.js
FROM node:14

# Створюємо робочий каталог
WORKDIR /usr/src/app

# Копіюємо файли з вашого проекту в контейнер
COPY package*.json ./
COPY index.js ./

# Встановлюємо залежності
RUN npm install


# Встановіть MySQL
RUN apt-get update && apt-get install -y mariadb-server

# Налаштуйте MySQL
RUN service mysql start && \
    mysql -e "CREATE DATABASE IF NOT EXISTS test_db_node;" && \
    mysql -e "CREATE USER 'admin'@'localhost' IDENTIFIED BY 'password';" && \
    mysql -e "GRANT ALL PRIVILEGES ON test_db_node.* TO 'admin'@'localhost';" && \
    mysql -e "FLUSH PRIVILEGES;"

# Запустіть додаток
CMD service mysql start && npm start

# Відкриваємо порт, на якому працює ваш сервер
EXPOSE 3000

